### ISSUE TITLE
python3 create_website.py to generate website， ERROR 'Permission denied'

### ISSUE THREAD

**Issue by lajiyuan** [erikbern/ann-benchmarks#225] opened 2021-03-23 03:34 UTC
Should we execute "chmod -R 777 results" after writing out the result folder every time, otherwise we will not have read permission and we cannot use create_website.py to generate a website？

**Comment by maumueller** [comment] 2021-03-23 10:02
The idea is to to run `create_website.py` with `sudo`. The docker container writes the result files as `root`, and `create_website.py` will cache some computations and needs write access to these files. @erikbern Maybe we should run the docker images as the actual user.

**Comment by erikbern** [comment] 2021-03-23 15:32
I think Docker generally likes to run as the superuser on a system, and I'm not sure if we have control over that, but I could be wrong?

My preference here would be to not mess around with permissions if possible. Maybe it's possible to write the website to a different directory or to mount a subdirectory of the results/ directory?

**Comment by maumueller** [comment] 2021-03-23 15:53
I think it's pretty straight-forward to do, see e.g., https://github.com/lemire/docker_programming_station/blob/master/Dockerfile#L21-L27, from https://lemire.me/blog/2020/05/22/programming-inside-a-container/. 

The problem is not with the website creation, but with the `hdf5` files being owned by `root`, and the metrics scripts trying to cache metrics by writing them into the `hdf5` file.

**Comment by erikbern** [comment] 2021-03-23 16:48
If it can be fixed in the Dockerfile, let's definitely do that. I didn't realize it was possible.

**Closed** 2022-11-21 08:57 UTC
